### ISSUE TITLE
New Device discovered in HA but no Entities

### ISSUE THREAD

**Issue by I-Lynx** [ginkage/MHI-AC-Ctrl-ESPHome#6]
Hi,

I've managed to successfully upload the D1 mini.
Home Assistant discovers a new device but there are no entities to control the AC.
I must be doing something wrong but I don't know what.
Do I need to add something in my configuration.yaml as well??

INFO Connecting to 10.0.14.46:6053 (10.0.14.46)
INFO Successfully connected to 10.0.14.46
[21:53:29][I][app:105]: ESPHome version 1.19.4 compiled on Jun 28 2021, 21:52:31
[21:53:29][C][wifi:484]: WiFi:
[21:53:29][C][wifi:344]:   SSID: '***'[redacted]
[21:53:29][C][wifi:345]:   IP Address: 10.0.14.46
[21:53:29][C][wifi:347]:   BSSID: 68:FF:7B:6F:6E:80[redacted]
[21:53:29][C][wifi:348]:   Hostname: 'airco'
[21:53:29][C][wifi:352]:   Signal strength: -62 dB ▂▄▆█
[21:53:29][C][wifi:356]:   Channel: 1
[21:53:29][C][wifi:357]:   Subnet: 255.255.255.0
[21:53:29][C][wifi:358]:   Gateway: 10.0.14.254
[21:53:29][C][wifi:359]:   DNS1: (IP unset)
[21:53:29][C][wifi:360]:   DNS2: (IP unset)
[21:53:29][C][logger:189]: Logger:
[21:53:29][C][logger:190]:   Level: DEBUG
[21:53:29][C][logger:191]:   Log Baud Rate: 0
[21:53:29][C][logger:192]:   Hardware UART: UART0
[21:53:29][C][mhi_ac_ctrl:043]: MHI-AC-Ctrl Climate 'MHI-AC-Ctrl'
[21:53:29][C][mhi_ac_ctrl:044]:   Min. Temperature: 16.0°C
[21:53:29][C][mhi_ac_ctrl:045]:   Max. Temperature: 36.0°C
[21:53:29][C][mhi_ac_ctrl:046]:   Supports HEAT: YES
[21:53:29][C][mhi_ac_ctrl:047]:   Supports COOL: YES
[21:53:29][C][ota:029]: Over-The-Air Updates:
[21:53:29][C][ota:030]:   Address: 10.0.14.46:8266
[21:53:29][C][api:095]: API Server:
[21:53:29][C][api:096]:   Address: 10.0.14.46:6053
[21:53:36][D][api.connection:630]: Client 'Home Assistant 2021.6.6 (10.0.14.6)' connected successfully!

**Comment by ginkage** [comment]
Does anything show up in "Configuration -> Integrations"?
You may need to click "Add Integration" and choose "ESPHome" if nothing is shown there.

**Comment by I-Lynx** [comment]
<img width="271" alt="Schermafbeelding 2021-06-28 om 22 00 38" src="https://user-images.githubusercontent.com/67384301/123696721-59cb0400-d85c-11eb-978d-baf61464c3d7.png">

Just a device with no entities

**Comment by ginkage** [comment]
Hm, looks like you're right. I'll need to check if something has changed in ESPHome itself, they could've broken something...

**Comment by I-Lynx** [comment]
I found a error in the HA logs:

Logger: homeassistant
Source: components/esphome/__init__.py:214 
First occurred: 22:17:03 (1 occurrences) 
Last logged: 22:17:03

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 214, in on_login
    entity_infos, services = await cli.list_entities_services()
  File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/client.py", line 137, in list_entities_services
    entities.append(cls(**kwargs))
  File "<attrs generated init aioesphomeapi.model.ClimateInfo>", line 9, in __init__
    self.supported_modes = __attr_converter_supported_modes(supported_modes)
  File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/model.py", line 245, in _convert_climate_modes
    return [ClimateMode(val) for val in value]
  File "/usr/local/lib/python3.8/site-packages/aioesphomeapi/model.py", line 245, in <listcomp>
    return [ClimateMode(val) for val in value]
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 6 is not a valid ClimateMode

**Comment by ginkage** [comment]
Interesting, it's definitely a valid mode: https://github.com/esphome/esphome/blob/dev/esphome/components/climate/climate_mode.h#L23
Gotta dig deeper.

**Comment by ginkage** [comment]
1 was changed to 6 here: https://github.com/esphome/esphome/commit/ebadaa966016dd9cfbc7fbd3046883ade9be0214#diff-3cc17e2d884f227c82605ff7dae5e504ab117f46f087e32030690e5c5ce350cf
this is probably the breaking change...

**Comment by ginkage** [comment]
...and the answer is probably: https://github.com/esphome/esphome/pull/1933
"the value for AUTO 6 was sent via protobuf but HA doesnt understand it yet"
Brilliant...

**Comment by ginkage** [comment]
OK, I've pushed a new commit, could you check if that works, please?

**Comment by I-Lynx** [comment]
It Works!!!

I have a entity and I can controll my AC.
Can't turn it off yet but I don't know if that is a known issue or not. 
Will dive in to that when I'm home from work.

**Comment by ginkage** [comment]
Oops. :)
That's what happens when you try to develop without a device to test on. I've added "off" to the list of supported modes, which might fix it.

**Comment by ginkage** [comment]
Cool, thank you for testing!
